const GET_SLIDES = 'GET_SLIDES';
const GET_SLIDES_SUCCESS = 'GET_SLIDES_SUCCESS';
const SET_ACTIVE_SLIDE = 'SET_ACTIVE_SLIDE';

export { GET_SLIDES };
export { SET_ACTIVE_SLIDE };
export { GET_SLIDES_SUCCESS };