const START_ANIMATION = 'START_ANIMATION';
const ANIMATION_COMPLETE = 'ANIMATION_COMPLETE';
const SET_SENTENCE = 'SET_SENTENCE';
const SET_ACTIVE_LETTERS = 'SET_ACTIVE_LETTERS';
const SET_PROGRESS_BAR = 'SET_PROGRESS_BAR';

export {START_ANIMATION}
export {ANIMATION_COMPLETE}
export {SET_SENTENCE}
export {SET_ACTIVE_LETTERS}
export {SET_PROGRESS_BAR}