const START_ANIMATION = 'START_ANIMATION';
const ANIMATION_COMPLETE = 'ANIMATION_COMPLETE';
const SET_PROGRESS_BAR = 'SET_PROGRESS_BAR';

export {START_ANIMATION}
export {ANIMATION_COMPLETE}
export {SET_PROGRESS_BAR}

export {SET_SENTENCE, SET_ACTIVE_LETTERS} from './letters/lettersTypes';